import random
import os
from colorama import Fore, init
init(convert=True)

Primarys = ["AK12",
          "AN-94",
          "AS VAL",
           "SCAR-L",
           "AUG A1",
           "M16A4",
           "G36",
           "M16A3",
           "AUG A2",
           "K2",
           "FAMAS F1",
           "AK47",
           "AUG A3",
           "L85A2",
           "HK416",
           "AK74",
           "AKM",
           "AK103",
           "TAR-21",
           "TYPE 88",
           "M231",
           "C7A2",
           "STG-44",
           "G11K2",
           "M14",
           "BEOWULF ECR",
           "SCAR-H",
           "AK12BR",
           "G3",
           "AG-3",
           "HK417",
           "HENRY 45-70",
           "FAL 50.00",
           "M4A1",
           "G36K",
           "M4",
           "L22",
           "SCAR PDW",
           "AKU12",
           "GROZA-1",
           "AK12C",
           "HONEY BADGER",
           "K1A",
           "SR-3M",
           "GROZA-4",
           "MC51SD",
            "FAL 50.63 PARA",
            "1858 CARBINE",
            "AK105",
            "JURY",
            "KAC SRR",
            "GYROJET CARBINE",
            "X95R",
            "HK51B",
            "KSG 12"
            "REMINGTON 870",
            "DBV12",
            "KS-23M",
            "SAIGA-12",
            "STEVENS DB",
            "E GUN",
            "AA-12",
            "SPAS-12",
            "DT11 PRO",
            "MP5K",
            "UMMP45",
            "G36C",
            "MP7",
            "MAC10",
            "P90",
            "MP5",
            "COLT SMG 633",
            "L2A3",
            "MP5SD",
            "MP10",
            "M3A1",
            "MP5/10",
            "UZI",
            "AUG A3 PARA",
            "K7",
            "KRINKOV",
            "PPSH-41",
            "FAL PARA SHORTY",
            "KRISS VECTOR",
            "PP-19 BIZON",
            "MP40",
            "X95 SMG",
            "TOMMY GUN",
            "RAMA 1130",
            "MK11",
            "SKS",
            "SL-8",
            "VSS VINTOREZ",
            "MSG90",
            "M21",
            "BEOWULF TCR",
            "SA58 SPR",
            "SCAR SSR",
            "COLT LMG",
            "M60",
            "AUG HBAR",
            "MG36",
            "RPK12",
            "L86 LSW",
            "RPK"
            "HK21",
            "SCAR HAMR",
            "RPG74",
            "MG3KWS",
            "INTERVENTION",
            "REMINGTON 700",
            "DRAGUNOV SVU",
            "AWS",
            "BFG 50",
            "AWM",
            "TRG-42"
            "MOSIN NAGANT",
            "DRAGUNOV SVDS",
            "K14",
            "HECATE II",
            "FT300",
            "M107",
            "STEYR SCOUT",
            "WA2000",
            "NTW-20",
           ]
Primary_Sights = [
  "DEFAULT SIGHT",
  "IRON SIGHT (if gun has)"
  "Z-POINT",
  "H&K SIGHT",
  "EOTECH XPS2",
  "FULL RING SIGHT",
  "DELTA SIGHT",
  "MARS",
  "EOTECH 552",
  "HALF RING SIGHT",
  "MINI SIGHT",
  "COMP AIMPOINT",
  "C79",
  "PK-A",
  "M145",
  "STEYR SIGHT",
  "MALCOLM 3X SIGHT",
  "PSO-1 SCOPE",
  "REFLEX SIGHT",
  "TA44 ACOG",
  "IZHMASH SIGHT",
  "KOBRA SIGHT",
  "SUPER SLIM SIGHT",
  "COYOTE SIGHT",
  "DIOPTER SIGHT",
  "ACOG SCOPE",
  "VCOG 6X SCOPE",
  "BUIS SIGHT",
  "MICRODOT MINI",
  "PILAD 3",
  "KEL-TEC SIGHT",
  "KALASHNIKOV SIGHT",
  "KAC SIGHT",
  "KOBRA EKP SIGHT",
  "TA33 ACOG",
  "MACRO P-1",
  "1200M SIGHT",
  "BARSKA ELECTRO",
  "KOUSAKU SIGHT",
  "H&K EXPORT SIGHT",
  "HERSTAL SIGHT",
  "HENSOLDT 3X SIGHT",
  "MICRODOT SRS",
  "BUNDESWEHR SIGHT",
  "OKP-7",
  "UH GEN1",
  "IWI SIGHT",
  "CARRY HANDLE SIGHT",
  "QUICK-RELEASE SIGHT",
  "MBUS SIGHT",
  "DDHB REFLEX",
  "AAC FLIP UP SIGHT",
  "HENSOLDT Z24",
  "DLC 120",
  "SWAROVSKI SCOPE",
  "DUAL APERTURE SIGHT",
  "KOUSAKU OLED SIGHT",
  "TA11 ACOG",
  "OEG",
  "MAGLITE",
  "PU-1 SCOPE",
  "AMT-TERMINATOR",
  "FF 3X NV",
  "PSO-1M2 SCOPE",
  "TA01 ACOG",
  "REFLECTOR SCOPE",
  "HANDMADE SIGHT",
  "VCOG 8X SCOPE",
  "SUSAT SCOPE",
  "ANIMU SIGHT",
  "GLOBAL OFFENCIVE SCOPE",
  "PLAGUE INSIGHT",
  "FURRO SIGHT",
  "👌👍",
  "ANTI SIGHT",
]
Primary_Barrels = [
  "SUPPRESSOR",
  "R2 SUPPRESSOR",
  "FLASH HIDER",
  "COMPENSATOR",
  "ARS SUPPRESSOR",
  "MUZZLE BREAK",
  "PBS-1 SUPPRESSOR",
  "PBS-4 SUPPRESSOR",
  "SHORT BARREL",
  "MUFFLER",
  "LOUDENER",
  "LONG BARREL",
  "OIL FILTER",
  "MUZZLE BOOSTER",
]
Primary_Underbarrels = [
  "FLASHLIGHT",
  "VERTICAL GRIP",
  "LASER",
  "ANGLED GRIP",
  "GREEN LASER",
  "POTATO GRIP",
  "SKELETON GRIP",
  "BLUE LASER",
  "FOLDING GRIP",
  "STUBBY GRIP",
  "PISTOL GRIP",
  "SIDEWAYS GRIP",
  "HERA COR GRIP",
  "CHAINSAW GRIP",
  "TRI LASER",
]
Primary_Other = [
  "FLASHLIGHT",
  "LASER",
  "GREEN LASER",
  "BLUE LASER",
  "CANTER IRON SIGHT",
  "CANTED DELTA SIGHT",
  "CANTED ACOG SCOPE",
  "TRI LASER",
  "BALLISTICS TRACKER",
  "CANTED ANIMU SIGHT",
  "CANTED FURRO SIGHT",
]
Melee = [
  "KNIFE",
  "TANTO",
  "WAR FAN",
  "GOSPELL BLADE",
  "NATA HATCHET",
  "MEK'LETH",
  "RITUAL SICKLE",
  "KAMA",
  "KEY",
  "MACHETE",
  "ICE PICK",
  "TOMAHAWK",
  "POCKET KNIFE",
  "CUTTER",
  "JASON",
  "BRIDAL BRANDISHER",
  "DARKHEART",
  "STEITER",
  "KOMMANDO",
  "LINKED SWORD",
  "HATTORI",
  "NAGINATA",
  "LONGSWORD",
  "FIRE AXE",
  "ZWEIHANDER",
  "CANDY CANE",
  "MAGLITE CLUB",
  "CROWBAR",
  "BARE FISTS",
  "ASP BATON",
  "BLOXY",
  "HOLIDAY TEA",
  "TRENCH MACE",
  "CLONKER",
  "NIGHTSTICK",
  "STUN GUN",
  "UCHINA",
  "FIXER",
  "BRASS KNUCKLE",
  "CRICKET BAT",
  "FRYING PAN",
  "ARM CANNON",
  "STARLIS FUNPOST",
  "HOCKEY STICK",
  "SWEEPER",
  "BASEBALL BAT",
  "PADDLE",
  "CURSED SHINAI",
  "BANJO",
  "STYLIS BRUSH",
  "KANABO",
  "STOPPER",
  "CLEMENTINE",
  "VOID STAFF",
  "MORNING STAR",
  "PRESENT",
]
Secondary = [
             "M9",
  "G17",
  "M1911",
  "DESERT EAGLE L5",
  "M45A1",
  "KG-99",
  "FIVE SEVEN",
  "ZIP 22",
  "IZHEVSK PB",
  "MAKAROV PM",
  "GB-22",
  "DESERT EAGLE XII",
  "GYROJET MARK I",
  "GSP",
  "G18",
  "93R",
  "TEC-9",
  "MICRO UZI",
  "SKORPION VZ.61",
  "MP1911",
  "ARM PISTOL",
  "MP412 REX",
  "MATEBA 6",
  "1858 NEW ARMY",
  "REDHAWK 44",
  "JUDGE",
  "EXECUTIONER",
  "SUPER SHORTY",
  "SFG 50",
  "M79 THUMPER",
  "COILGUN",
  "SAWED OFF",
  "SAIGA-12U",
  "OBREZ",
]
Secondary_Sights = [
  "DEFAULT SIGHT",
  "IRON SIGHT (if gun has)"
  "Z-POINT",
  "H&K SIGHT",
  "EOTECH XPS2",
  "FULL RING SIGHT",
  "DELTA SIGHT",
  "MARS",
  "EOTECH 552",
  "HALF RING SIGHT",
  "MINI SIGHT",
  "COMP AIMPOINT",
  "C79",
  "PK-A",
  "M145",
  "STEYR SIGHT",
  "MALCOLM 3X SIGHT",
  "PSO-1 SCOPE",
  "REFLEX SIGHT",
  "TA44 ACOG",
  "IZHMASH SIGHT",
  "KOBRA SIGHT",
  "SUPER SLIM SIGHT",
  "COYOTE SIGHT",
  "DIOPTER SIGHT",
  "ACOG SCOPE",
  "VCOG 6X SCOPE",
  "BUIS SIGHT",
  "MICRODOT MINI",
  "PILAD 3",
  "KEL-TEC SIGHT",
  "KALASHNIKOV SIGHT",
  "KAC SIGHT",
  "KOBRA EKP SIGHT",
  "TA33 ACOG",
  "MACRO P-1",
  "1200M SIGHT",
  "BARSKA ELECTRO",
  "KOUSAKU SIGHT",
  "H&K EXPORT SIGHT",
  "HERSTAL SIGHT",
  "HENSOLDT 3X SIGHT",
  "MICRODOT SRS",
  "BUNDESWEHR SIGHT",
  "OKP-7",
  "UH GEN1",
  "IWI SIGHT",
  "CARRY HANDLE SIGHT",
  "QUICK-RELEASE SIGHT",
  "MBUS SIGHT",
  "DDHB REFLEX",
  "AAC FLIP UP SIGHT",
  "HENSOLDT Z24",
  "DLC 120",
  "SWAROVSKI SCOPE",
  "DUAL APERTURE SIGHT",
  "KOUSAKU OLED SIGHT",
  "TA11 ACOG",
  "OEG",
  "MAGLITE",
  "PU-1 SCOPE",
  "AMT-TERMINATOR",
  "FF 3X NV",
  "PSO-1M2 SCOPE",
  "TA01 ACOG",
  "REFLECTOR SCOPE",
  "HANDMADE SIGHT",
  "VCOG 8X SCOPE",
  "SUSAT SCOPE",
  "ANIMU SIGHT",
  "GLOBAL OFFENCIVE SCOPE",
  "PLAGUE INSIGHT",
  "FURRO SIGHT",
  "👌👍",
  "ANTI SIGHT",
]
Secondary_Barrels = [
  "SUPPRESSOR",
  "R2 SUPPRESSOR",
  "FLASH HIDER",
  "COMPENSATOR",
  "ARS SUPPRESSOR",
  "MUZZLE BREAK",
  "PBS-1 SUPPRESSOR",
  "PBS-4 SUPPRESSOR",
  "SHORT BARREL",
  "MUFFLER",
  "LOUDENER",
  "LONG BARREL",
  "OIL FILTER",
  "MUZZLE BOOSTER",
]
Secondary_Underbarrel = [
  "FLASHLIGHT",
  "VERTICAL GRIP",
  "LASER",
  "ANGLED GRIP",
  "GREEN LASER",
  "POTATO GRIP",
  "SKELETON GRIP",
  "BLUE LASER",
  "FOLDING GRIP",
  "STUBBY GRIP",
  "PISTOL GRIP",
  "SIDEWAYS GRIP",
  "HERA COR GRIP",
  "CHAINSAW GRIP",
  "TRI LASER",
]
Secondary_Other = [
  "FLASHLIGHT",
  "LASER",
  "GREEN LASER",
  "BLUE LASER",
  "CANTER IRON SIGHT",
  "CANTED DELTA SIGHT",
  "CANTED ACOG SCOPE",
  "TRI LASER",
  "BALLISTICS TRACKER",
  "CANTED ANIMU SIGHT",
  "CANTED FURRO SIGHT",
]


Quit = ""
while Quit != True:
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Fore.LIGHTBLUE_EX + "                   ~Made by Lx#8450~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

    print(Fore.LIGHTBLUE_EX + "    ~If an attachment doesnt fit on gun use default~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Fore.LIGHTBLUE_EX + "                       ~Primary~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

    chosen_main = random.choice(Primarys)
    chosen_sight = random.choice(Primary_Sights)
    chosen_barrel = random.choice(Primary_Barrels)
    chosen_underbarrel = random.choice(Primary_Underbarrels)
    chosen_other = random.choice(Primary_Other)

    print(Fore.LIGHTRED_EX + chosen_main)
    print(Fore.LIGHTRED_EX + chosen_barrel)
    print(Fore.LIGHTRED_EX + chosen_underbarrel)
    print(Fore.LIGHTRED_EX + chosen_other)

    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Fore.LIGHTBLUE_EX + "                       ~Secondary~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")


    chosen_secondarys = random.choice(Secondary)
    chosen_secondary_sights = random.choice(Secondary_Sights)
    chosen_secondary_barrel = random.choice(Secondary_Barrels)
    chosen_secondary_underbarrel = random.choice(Secondary_Underbarrel)
    chosen_secondary_other = random.choice(Secondary_Other)
    
    print(Fore.LIGHTRED_EX + chosen_secondary_barrel)
    print(Fore.LIGHTRED_EX + chosen_secondary_underbarrel)
    print(Fore.LIGHTRED_EX + chosen_secondary_other)

    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Fore.LIGHTBLUE_EX + "                       ~Melee~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

    chosen_melee = random.choice(Melee)

    print(Fore.LIGHTRED_EX + chosen_melee)
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Fore.LIGHTBLUE_EX + r"                     Regen? Y\N~~")
    print(f"{Fore.RESET}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    restart_input = input("\n-------: ")

    if restart_input.lower() == 'yes' or restart_input.lower() == 'y':
        Quit = False
        os.system('cls')
    else:
        os.system('pause')
        Quit = True
